-- Add to existing init.sql
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  phone_number VARCHAR(15) UNIQUE NOT NULL,
  verification_code VARCHAR(6),
  verification_expires TIMESTAMP,
  is_verified BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE memories 
ADD COLUMN user_id VARCHAR(36),
ADD COLUMN nsfw_score FLOAT DEFAULT 0,
ADD FOREIGN KEY (user_id) REFERENCES users(id);